project:
  name: SFTrainer
  author: Yuvraj Singh
  version: 1.0

Dataset:
    dataset_path: str = ""
    batch_size: int = 16
    num_workers: int = 0
    shuffle: bool = True
    drop_last: bool = False
    pin_memory: bool = True
    persistent_workers: bool = True
    use_hf_dataset: bool = False

Model:
  model_path: str = ""
  epochs: int = 1
  eval_iters: int = 10

MAP:
  use_bfloat16: bool = False
  use_float16: bool = False

Optimizations:
  use_compile: bool = False

Scheduler:
  use_scheduler: bool = False 
  type: str = "cosine"
