project:
  name: SFTrainer
  author: Yuvraj Singh
  version: 1.0


Dataset:
    use_hf_dataset: True
    dataset_path: stanfordnlp/imdb
    max_length: 128
    batch_size:  16
    num_workers:  4
    shuffle:  True
    drop_last: True
    pin_memory:  True
    persistent_workers:  True
   
huggingface:
  hf_token: "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"

Model:
  model_path: ""
  epochs: 1
  eval_iters: 10
  tokenizer: ""

MAP:
  use_bfloat16:  False
  use_float16: True

Optimizations:
  use_compile: False


wandb:
  project_name: "SFTrainer"
  

